### ISSUE TITLE
FreeBuds 3

### ISSUE THREAD

**Issue by vladislav06** [melianmiko/OpenFreebuds#1]
dont work with FreeBuds 3.
when i tap on " FreeBuds 3" device in device list, nothing happens.

**Comment by vladislav06** [comment]
it would be cool if you add some kind of driver, for command mapping for different devices!

**Comment by melianmiko** [comment]
HUAWEI FreeBuds 3 uses totally another protocol for communication with app. I don't have this device, and without them, i can't implement support of it. Sorry.

**Comment by vladislav06** [comment]
sad, txh for answer
