### ISSUE TITLE
`openfreebuds mode_X` works, but says it doesn't

### ISSUE THREAD

**Issue by TheLastGimbus** [melianmiko/OpenFreebuds#10]
Hi again!
I'm on Arch Linux with gnome on wayland. Got the tray icon to work thanks to https://extensions.gnome.org/extension/615/appindicator-support/

I wanted to set up keeb shortcuts, but when I launch `openfreebuds mode_X`, it ALWAYS pops up that device is not configured/http server is broken - but it's not, and headphones *do change* the mode (i hear it):

![image](https://user-images.githubusercontent.com/40139196/210259531-89b2e65e-00ee-4eda-9a94-1c2248742147.png)

```
openfreebuds mode_1
WARNING:root:Application already started, pid 23979
ERROR:OfbLauncher:Can't do command via HTTP-server
```

**Comment by melianmiko** [comment]
Hm, maybe I broke this feature in the last update. I'll check that in a few days.

**Comment by melianmiko** [comment]
Fixed
