### ISSUE TITLE
Multi-User compatibility for Linux

### ISSUE THREAD

**Issue by S-trace** [melianmiko/OpenFreebuds#14]
Hi!

I am using my PC with two user accounts (work account and home account) and using CTRL+ALT+F1 and CTRL+ALT+F2 to switch virtual terminals between work and home accounts. OpenFreebuds does not work well if it is started on both user accounts.

I think it should be a core module (a singleton that takes care of devices connectivity) and UI modules (which provide information and are connected to the core module).

Is it possible to refactor OpenFreebuds in such a way to make it compatible with multi-user systems?

Thanks!

**Comment by melianmiko** [comment]
Will be resolved in `next` release.

![image](https://github.com/user-attachments/assets/5e63b7bb-c13c-4d48-a4cc-292743ffca5e)

**Comment by melianmiko** [comment]
Resolved, after v0.14 release OpenFreebuds will work in multi-user / multi-v-term mode. If you want to try it now, you could grab [test binaries](https://github.com/melianmiko/OpenFreebuds/actions) from GH Actions.

Will close this issue after release.
