### ISSUE TITLE
The right-click menu cannot be clicked

### ISSUE THREAD

**Issue by xieincz** [melianmiko/OpenFreebuds#16]
In Windows 11, you can open a menu by right-clicking the icon in the notification bar. But can't click any item in the menu. In other words, the menu closes after clicking any item, but it doesn't take effect.

**Comment by melianmiko** [comment]
Hi,

Can't reproduce this bug. Installed a fresh copy of Windows 11 in VirtualBox, and all works well. Did you tried to restart application and/or Windows?

https://user-images.githubusercontent.com/67851274/236790392-b6e53fd2-fc18-4c92-9734-8e02cd5b0226.mp4

**Comment by xieincz** [comment]
Restarting the app does work. Before it was the first run after installation.
