### ISSUE TITLE
Freebuds SE Support

### ISSUE THREAD

**Issue by avsar-master** [melianmiko/OpenFreebuds#17]
Hello Sir,

I have this device right now and how can I add it to supported list? Do I need to capture the HCI packets and send them to you as in link you shared, if necessary, where should I send them?

**Comment by melianmiko** [comment]
Yes, you can record HCI traffic, if you want to see this model in OpenFreebuds supported devices. But, unfortunately, I currently was busy with other projects, so I'll check your recorded data only in a few weeks...

How-to record: https://mmk.pw/en/posts/ofb-contribution/
You can send collected data to my EMail: support@mmk.pw

**Comment by avsar-master** [comment]
Thank you for your reply, I'm sending the package dump and the video I recorded on same time to your e-mail.
