### ISSUE TITLE
Publish to F-Droid?

### ISSUE THREAD

**Issue by natrius** [melianmiko/OpenFreebuds#18]
As an open source app it might be worth thinking about publishing on https://f-droid.org/. Information about it in the docs https://f-droid.org/en/docs/

It might even be possible to get it beforehand on https://android.izzysoft.de/repo if you need help or if something is unclear. Izzy is usally really helpfull and awesome at supporting app developers to get their app to f-droid :)

**Comment by melianmiko** [comment]
OpenFreebuds is an application for Windows & Linux, it isn't available for android bow, so couldn't be published to F-Droid.

**Comment by natrius** [comment]
Oh, apology, i thought i read android. I might have picked the wrong project for this issue, i apologize 🙈

**Comment by melianmiko** [comment]
No problem.
Looks like you searched for FreeBuddy app repository.
