### ISSUE TITLE
Freebuds Pro

### ISSUE THREAD

**Issue by sermart1234** [melianmiko/OpenFreebuds#2]
How can I help add support? How did you reverse engineer the protocol?

**Comment by melianmiko** [comment]
Is your offer of help still valid?

**Comment by pillo79** [comment]
I have the Freebuds Pro and am interested in giving it a try :+1:

**Comment by melianmiko** [comment]
Hi, @pillo79 

I could try to implement the support of this device, if you'll dump bluetooth traffic of official Ai Life. With these files I'll be able to extract and analyze which commands they use to manage your device.

Here's a short guide: https://melianmiko.ru/en/posts/ofb-contribution/

Sorry for my bad English =)

**Comment by pillo79** [comment]
Thanks, I will look into that and send you the logs! No worries :-)

**Comment by melianmiko** [comment]
Released OpenFreebuds 0.13 with initial support of FreeBuds Pro.

Features from @pillo79's  dump that has been added and should fully work:
- Noise cancellation setting with cancellation levels (including dynamic) and "voice boost" for awareness;
- Long tap action configuration with separate setting for left and right bud.
- Device information & battery level fetch (no difference with 4i/5i).

Some settings are missing in dump file, but should match with other device models:
- Swipe action settings from 5i;
- Voice language, double tap settings from 4i.

Waiting for feedback, how it will this work on a real device. What about "dual connect" and priority device setting, I think it will also match with 5i, but I forgot to check & enable them, will return to this question a bit later.

**Comment by pillo79** [comment]
Thanks! I confirm that the Freebuds Pro are recognized and lots of data is readable (firmware info, battery values, current ANC setting etc). Changing ANC,voice language (only EN or CH) and double tap / long tap works. I have not found the dual connect / priority stuff in the UI though! :sweat_smile:

**Comment by melianmiko** [comment]
Released v0.13.1 with enabled dual-connect & prior device settings.

As I know, all settings of FreeBuds Pro is now added to OpenFreebuds, so I'll close this issue. If you found any other bugs, feel free to write here or in new issue.
