### ISSUE TITLE
Windows: добавить проверку наличия WMIC

### ISSUE THREAD

**Issue by dartraiden** [melianmiko/OpenFreebuds#21]
В Windows 11 WMIC является опциональным компонентом и может быть удалён пользователем.

https://github.com/melianmiko/OpenFreebuds/blob/546a8d25eb66d54b48e2b5ea7a2fd76296f5d58f/src/openfreebuds_backend/windows/misc_win32.py#L33C1-L33C51

Сейчас в такой ситуации приложение просто падает. Лучше реализовать проверку и выдавать сообщение пользователю об отсутствующем компоненте.

**Comment by melianmiko** [comment]
По идее Windows сам проверяет её наличие и включает при первой же попытке запуска, однако тут проблема в другом. Его впринципе [собираются выпилить](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/ba-p/4039242), надо переходить на что-то другое.

Займусь этим на неделе, хотя сначала надо бы саму винду поставить...
