### ISSUE TITLE
Freebuds 5i

### ISSUE THREAD

**Issue by django228** [melianmiko/OpenFreebuds#23]
Изначально репорт написал на английском.
Только сейчас понял, что вроде ведь классные русскоязычные ребята делают это чудо) 
Пользовался приложением на протяжении 3-4 дней бесперебойно, но сегодня при открытии приложения возникает эта ошибка. 
   _____             _____             _         _     
  |     |___ ___ ___|   __|___ ___ ___| |_ _ _ _| |___ 
  |  |  | . | -_|   |   __|  _| -_| -_| . | | | . |_ -|
  |_____|  _|___|_|_|__|  |_| |___|___|___|___|___|___|
        |_|                                            

         OpenFreebuds crashed due to unknown error.

  If you don't know why this happened, you coul'd try to
   send this log to developer, and they will try to do
  something to prevent this failure in future versions.

E-Mail: support@mmk.pw  -or-  Web: https://mmk.pw/en/mailto

app_version=0.13.1
python_version=sys.version_info(major=3, minor=11, micro=7, releaselevel='final', serial=0)
os_platform=Linux-6.7.0-arch3-1

-= Settings file =-
{
  "address": "A4:46:B4:B8:A9:9F",
  "device_name": "HUAWEI FreeBuds 5i",
  "is_device_mocked": false,
  "device_autoconfig": true,
  "language": "ru_RU",
  "theme": "dark",
  "icon_theme": "auto",
  "first_run": false,
  "modules": {
    "hotkeys": {
      "enabled": true,
      "next_mode": "<ctrl>+<alt>+q"
    },
    "http_server": {
      "enabled": false,
      "external_access": false,
      "port": 21201
    },
    "mpris_helper": {
      "enabled": false
    },
    "update_check": {
      "enabled": true
    }
  },
  "context_menu_extras": [
    "equalizer",
    "dual_connect"
  ]
}

-= Manager state =-
device_name=HUAWEI FreeBuds 5i
device_addr=A4:46:B4:B8:A9:9F
state=4
device_class=<openfreebuds.device.huawei.profiles.buds_5i.FreeBuds5iDevice object at 0x7e3a8a647dd0>

-= Device state =-
{
  "info": {
    "field_2": "\u0001E",
    "device_ver": "HL1OTEM2_VA",
    "software_ver": "HarmonyOS 2.1.0.202(F001H003C90)",
    "serial_number": "5PUTQ23B17004613",
    "device_model": "BTFT0014-000145",
    "ota_version": "BTFT0014",
    "field_24": "L-TQ908423BF010631,R-TQ908823BD013002",
    "field_25": "\u0001"
  },
  "state": {
    "in_ear": false
  },
  "battery": {
    "global": 15,
    "left": 15,
    "right": 15,
    "case": 1,
    "is_charging": false
  },
  "anc": {
    "mode": "cancellation",
    "mode_options": "normal,cancellation,awareness",
    "level": "normal",
    "level_options": "comfort,normal,ultra"
  },
  "action": {
    "double_tap_left": "tap_action_pause",
    "double_tap_right": "tap_action_pause",
    "double_tap_options": "tap_action_pause,tap_action_prev,tap_action_next,tap_action_assistant,tap_action_off",
    "double_tap_in_call": "tap_action_answer",
    "double_tap_in_call_options": "tap_action_off,tap_action_answer",
    "long_tap_left": "tap_action_switch_anc",
    "long_tap_right": "tap_action_switch_anc",
    "long_tap_options": "tap_action_off,tap_action_switch_anc",
    "noise_control_left": "noise_control_off_on_aw",
    "noise_control_right": "noise_control_off_on_aw",
    "noise_control_options": "noise_control_off_on,noise_control_off_on_aw,noise_control_on_aw,noise_control_off_an",
    "swipe_gesture": "tap_action_change_volume",
    "swipe_gesture_options": "tap_action_off,tap_action_change_volume"
  },
  "config": {
    "auto_pause": true,
    "sound_quality_preference": "sqp_connectivity",
    "sound_quality_preference_options": "sqp_quality,sqp_connectivity",
    "preferred_device": "000000000000"
  },
  "dev_name": {},
  "dev_auto_connect": {},
  "dev_connected": {}
}

-= Entire application log =-
DEBUG:FreebudsLocale:MainThread  Using language ru_RU
INFO:LinuxBackend:MainThread  System theme name is Breeze
DEBUG:AppletIcons:MainThread  set theme=dark
INFO:Applet:MainThread  Loading all modules...
DEBUG:HotkeysTool:MainThread  Starting hotkey tool...
DEBUG:HotkeysTool:MainThread  Started hotkey tool.
INFO:AppletModule:Thread-2 (_thread)  Starting module update_check
DEBUG:UpdateChecker:Thread-2 (_thread)  0.13.1
INFO:Applet:Thread-3 (_thread)  Started
INFO:Applet:Thread-3 (_thread)  Attach recently used device, mac=A4:46:B4:B8:A9:9F
DEBUG:FreebudsManager:Thread-3 (_thread)  Waiting for finish current manager...
INFO:FreebudsManager:Thread-3 (_thread)  Don't started, nothing to close
DEBUG:FreebudsManager:Thread-3 (_thread)  Running mainloop via safe wrapper
DEBUG:FreebudsManager:Thread-4 (_thread)  Started
INFO:Applet:Thread-3 (_thread)  Change icon: state_no_dev
INFO:FreebudsManager:Thread-4 (_thread)  Trying to create device and connect...
INFO:AutoConfig:Thread-3 (_thread)  Set device HUAWEI FreeBuds 5i A4:46:B4:B8:A9:9F
INFO:FreebudsManager:Thread-4 (_thread)  State changed to 3
INFO:FreebudsManager:Thread-3 (_thread)  Device already attached, ignoring set_device
INFO:Applet:Thread-3 (_thread)  Change icon: state_wait
ERROR:GenericSPPDevice:Thread-4 (_thread)  

Can't fetch service info from device, err: No module named 'bluetooth'
Looks like pybluez didn't installed or didn't work as expected.
Using fallback port number 16
  
DEBUG:GenericSPPDevice:Thread-4 (_thread)  Starting via safe wrapper
INFO:GenericSPPDevice:Thread-6 (_thread)  starting recv...
DEBUG:GenericSPPDevice:Thread-4 (_thread)  Starting via safe wrapper
INFO:GenericSPPDevice:Thread-7 (_thread)  starting send thread...
DEBUG:GenericSPPDevice:Thread-4 (_thread)  Starting via safe wrapper
INFO:GenericSPPDevice:Thread-8 (_thread)  starting handle...
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler device_info...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=0107, param_0=b'', param_1=b'', param_2=b'', param_3=b'', param_4=b'', param_5=b'', param_6=b'', param_7=b'', param_8=b'', param_9=b'', param_10=b'', param_11=b'', param_12=b'', param_13=b'', param_14=b'', param_15=b'', param_16=b'', param_17=b'', param_18=b'', param_19=b'', param_20=b'', param_21=b'', param_22=b'', param_23=b'', param_24=b'', param_25=b'', param_26=b'', param_27=b'', param_28=b'', param_29=b'', param_30=b'', param_31=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=0a0e, param_1=b'\x00'
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  Got unsupported package
command=0a0e, param_1=b'\x00'
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=0107, param_2=b'\x01E', param_3=b'HL1OTEM2_VA', param_7=b'HarmonyOS 2.1.0.202(F001H003C90)', param_9=b'5PUTQ23B17004613', param_10=b'BTFT0014-000145', param_15=b'BTFT0014', param_24=b'L-TQ908423BF010631,R-TQ908823BD013002', param_25=b'\x01'
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler tws_in_ear...
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler battery...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=0108, param_1=b'', param_2=b'', param_3=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=0108, param_1=b'\x0f', param_2=b'\x0f\x0f\x01', param_3=b'\x00\x00\x00', param_4=b'\x14\n'
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler anc_global...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2b2a, param_1=b'', param_2=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=2b2a, param_1=b'\x00\x01'
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler gesture_double...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=0120, param_1=b'', param_2=b'', param_3=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=0120, param_1=b'\x01', param_2=b'\x01', param_3=b'\x01\x07\x02\x00\xff', param_4=b'\x00', param_6=b'\x00\xff'
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler gesture_long_split...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2b17, param_1=b'', param_2=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=2b17, param_1=b'\n', param_2=b'\n', param_3=b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0e\x0f', param_4=b'\x00', param_6=b'\x00\xff'
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2b19, param_1=b'', param_2=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=2b19, param_1=b'\x02', param_2=b'\x02', param_3=b'\x01\x02\x03\x04\x05\x06\x07\x08\t\n'
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler gesture_swipe...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2b1f, param_1=b'', param_2=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=2b1f, param_1=b'\x00', param_3=b'\x00\xff'
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler tws_auto_pause...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2b11, param_1=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=2b11, param_1=b'\x01'
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler config_sound_quality...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2ba3, param_1=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=2ba3, param_1=b'\x01', param_2=b'\x01'
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler config_eq...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2b4a, param_2=b''
DEBUG:GenericHuaweiSppDevice:Thread-8 (_thread)  recv command=2b4a, param_1=b'\x01', param_2=b'\t', param_3=b'\x01\x02\x03\t', param_4=b'\x01'
ERROR:RunSafe:Thread-8 (_thread)  Action SPPDevice failed.
Traceback (most recent call last):
  File "/opt/openfreebuds/openfreebuds_applet/utils.py", line 74, in _internal
    func(*args, **kwargs)
  File "/opt/openfreebuds/openfreebuds/device/generic/spp_device.py", line 117, in _thread_handle
    self.do_data_handle(data)
  File "/opt/openfreebuds/openfreebuds/device/huawei/generic/spp_device.py", line 109, in do_data_handle
    self.on_package(pkg)
  File "/opt/openfreebuds/openfreebuds/device/huawei/generic/spp_device.py", line 84, in on_package
    self._on_package[pkg.command_id].on_package(pkg)
  File "/opt/openfreebuds/openfreebuds/device/huawei/spp_handlers/config_equalizer.py", line 46, in on_package
    self.w_presets[value])
    ~~~~~~~~~~~~~~^^^^^^^
KeyError: 9
DEBUG:TkinterTools:Thread-9 (th)  Starting UI thread...
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler dual_connect_toggle...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2b2f, param_1=b''
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler dual_connect_devices...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2b31, param_1=b''
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=2b31, param_1=b''
INFO:GenericHuaweiSppDevice:Thread-4 (_thread)  Attach handler voice_language...
DEBUG:GenericHuaweiSppDevice:Thread-4 (_thread)  send command=0c02, param_1=b'', param_3=b''
INFO:AppletModule:Thread-2 (_thread)  Module update_check exited.
WARNING:GenericHuaweiSppDevice:Thread-4 (_thread)  Too long read wait, maybe command is ignored
INFO:FreebudsManager:Thread-4 (_thread)  State changed to 4
INFO:Applet:Thread-3 (_thread)  Change icon: connected_cancellation_15


![image](https://github.com/melianmiko/OpenFreebuds/assets/98344405/da681df2-bd29-427b-beb5-ee5f4fe11f1a)

**Comment by melianmiko** [comment]
Проблема уже известная, исправлю в ближайшем обновлении. Если вкратце, падает программа из-за того, что выбран неизвестный ей пресет эквалайзера. Так что решение простое: через Ai Life сменить пресет на один из стандартных (отключен, усиление баса или усиление высоких).

Хотя очень странно, как на 5i можно выбрать какой-то иной, если их всего три...

**Comment by django228** [comment]
не совсем

**Comment by django228** [comment]
у меня есть подозрения, что приложуха дропается после смены кодека

**Comment by django228** [comment]
ошибка возникла, когда зашел в дискорд и кодек сменился с LDAC на гарнитурный кодек mSBC

**Comment by melianmiko** [comment]
Видимо при переходе на этот кодек эквалайзер отключается, потому происходит такой неадекват. Разберёмся, благо 5i у знакомого могу на тесты взять.

**Comment by django228** [comment]
возможно и так, поиграйтесь с A2DP. спасибо за вашу работу!
