### ISSUE TITLE
Option to display charge in the tray

### ISSUE THREAD

**Issue by T3sT3ro** [melianmiko/OpenFreebuds#28]
Hi, would it be possible to add an option to display battery charge directly in the tray next to the icon (+toggle for settings via settings), in a similar fashion to how the notebook battery charge is displayed?

![image](https://github.com/user-attachments/assets/fdc81416-5bd6-4365-93d7-cb74d247cd80)

showing something like `Ⓛ 100%  Ⓡ 100%  ⬬ 80%`?

**Comment by melianmiko** [comment]
Displaying text near icon isn't possible for third party apps, at least in GNOME and Windows.
