### ISSUE TITLE
Spam in `journalctl`

### ISSUE THREAD

**Issue by T3sT3ro** [melianmiko/OpenFreebuds#29]
The following lines are logged every several seconds to the journal when the headphones are closed and nearby the laptop, when the bluetooth is ON:

```
wrz 04 14:48:21 xxxxxx openfreebuds.desktop[7623]: INFO:HuaweiHandlers:Thread-13 (_thread)  Timed out waiting device enumeration, retry...
wrz 04 14:48:21 xxxxxx openfreebuds.desktop[7623]: DEBUG:GenericHuaweiSppDevice:Thread-13 (_thread)  send command=2b31, param_1=b''
```

**Comment by melianmiko** [comment]
Reduced CLI / journalctl logging level to warnings and errors only, will be available since v0.14 release.
