### ISSUE TITLE
Module bluetooth not found

### ISSUE THREAD

**Issue by sermart1234** [melianmiko/OpenFreebuds#3]
```
[sermart1234@fedora ~]$ openfreebuds 
Traceback (most recent call last):
  File "/usr/bin/openfreebuds", line 5, in <module>
    import ofb_launcher
  File "/opt/openfreebuds/ofb_launcher.py", line 10, in <module>
    from openfreebuds import event_bus, manager, cli_io
  File "/opt/openfreebuds/openfreebuds/manager.py", line 6, in <module>
    import openfreebuds.device
  File "/opt/openfreebuds/openfreebuds/device/__init__.py", line 2, in <module>
    from openfreebuds.device.profile_freebuds_4i import FreeBuds4iDevice
  File "/opt/openfreebuds/openfreebuds/device/profile_freebuds_4i.py", line 2, in <module>
    from openfreebuds.device.huawei_spp_device import HuaweiSPPDevice
  File "/opt/openfreebuds/openfreebuds/device/huawei_spp_device.py", line 8, in <module>
    from openfreebuds.device.spp_protocol import SppProtocolDevice
  File "/opt/openfreebuds/openfreebuds/device/spp_protocol.py", line 8, in <module>
    import bluetooth
ModuleNotFoundError: No module named 'bluetooth'
```

```
[sermart1234@fedora]$ sudo pip3 install pybluez
Collecting pybluez
  Using cached PyBluez-0.23.tar.gz (97 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PyBluez setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by melianmiko** [comment]
Looks like pybluez is finally broken...
Try to install `pybluez2` instead of `pybluez`, this is a fork with some fixes.
Later I'll fully migrate app to this version...

**Comment by sprootik** [comment]
Hi. Python version 3.10.7. 
also faced the same problem. Installed pybluez like this
pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez 
but when i try to run:
```
  File "<...>/openfreebuds/OpenFreebuds_Desktop/builddir/openfreebuds/openfreebuds/device/spp_protocol.py", line 76, in _connect_socket
    self.socket = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

```
If i install pybluez2
File "<...>/site-packages/bluetooth/native_socket.py", line 7, in <module>
    Protocols.RFCOMM: socket.BTPROTO_RFCOMM
AttributeError: module 'socket' has no attribute 'BTPROTO_RFCOMM'

installing from deb packages or ubuntu repo also doesn't work.

**Comment by melianmiko** [comment]
> Hi. Python version 3.10.7. 
> also faced the same problem. Installed pybluez like this
> pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez 
> but when i try to run:
> ```
>   File "<...>/openfreebuds/OpenFreebuds_Desktop/builddir/openfreebuds/openfreebuds/device/spp_protocol.py", line 76, in _connect_socket
>     self.socket = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM,
> AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
> 
> ```
> If i install pybluez2
> File "<...>/site-packages/bluetooth/native_socket.py", line 7, in <module>
>     Protocols.RFCOMM: socket.BTPROTO_RFCOMM
> AttributeError: module 'socket' has no attribute 'BTPROTO_RFCOMM'
> 
> installing from deb packages or ubuntu repo also doesn't work.

Which distro you use?
Looks like your `python3` was build without bluetooth socket support:

**Comment by melianmiko** [comment]
Problem should be fixed now.
Use `pybluez-edge` instead of `pybluez` or `pybluez2`, because both of them PyPi packages was broken.
Please notice that you  may need to install some C compiler and `libbluetooth-dev` package for that.
