### ISSUE TITLE
Unwanted beeps when connecting devices

### ISSUE THREAD

**Issue by ZiuChen** [melianmiko/OpenFreebuds#4]
非常棒的软件！
但我在使用中还遇到了一点小问题：
- 如果我的Freebuds 4i已经连接到电脑上，当我在OpenFreebuds选择“断开连接”时，设备正常断开
- 如果Freebuds 4i并没有连接，我在OpenFreebuds选择“连接设备”时，设备中都会播放三次“滴”声，分别代表：连接上了、已断开，连接上了
这不是什么大问题，但是每次连接状态切换时Freebuds 4i中都会播放一个“滴”的音乐，在蓝牙设置面板中我发现，耳机展示了三种状态：已配对 -> 已连接 -> 已连接语音，音乐

我不知道您在使用的时候有没有遇到这个问题，我想知道这是我的原因还是软件的原因 谢谢！💖

****

Execllent work!
But I also encountered a little problem in use:

- If my Freebuds 4i is already connected to the computer, when I select "Disconnect" in OpenFreebuds, the device disconnects normally.
- If the Freebuds 4i is not connected, when I select "connect device" in OpenFreebuds, the device will play three beeps, which means: connected, disconnected, connected.

This isn't a big deal, but every time the connection state switches, a "beep" will play in the Freebuds 4i, and in the bluetooth settings panel I found that the headphones show three states: paired -> connected -> connected voice, music.

I don't know if you have encountered this problem when you are using it, I want to know if this is my reason or the software's reason Thank you!💖

****

Windows10 x86 with Bluetooth Command Line Tools installed

**Comment by melianmiko** [comment]
hi,
I will check that when will the time...
