### ISSUE TITLE
Freebuds 6i (willing to help)

### ISSUE THREAD

**Issue by Fares-Elkady** [melianmiko/OpenFreebuds#43]
Just got the Freebuds 6i and was bummed not to find compatibility.
Would be great if you added that + I'm willing to help with bluetooth logs or maybe some development too :P

**Comment by melianmiko** [comment]
Hi,

Would be great if you'll make a Bluetooth traffic dump & video as described in [this post](https://mmk.pw/en/posts/ofb-contribution/), I'll look it and check what's required to add 6i support to OpenFreebuds.

**Comment by Fares-Elkady** [comment]
I emailed you both the Bluetooth traffic dump & the video on your support email "support@mmk.pw". If you need anything else let me know.

**Comment by melianmiko** [comment]
Received your email, will dive into it in a few days, thank you.

**Comment by melianmiko** [comment]
Looked through your dump, and it seems that 5i & 6i works absolutely identical, only differences are port number (6i configuration port is `1`, which is same as for Pro series, 5i is at `16`), and 6i has two additional equalizer presets.

Fun fact is that this new equalizer presets (Symphony and Hi-Fi Live) aren't built into device, they are stored into AI Life application and sends to device exactly as custom presets, so it could be ported to other models, like FreeLace Pro 2 or Freebuds Pro 3.

**Comment by melianmiko** [comment]
Added initial implementation of 6i support, if you want to try, you could grab windows / debian-ubuntu test packages from [github actions](https://github.com/melianmiko/OpenFreebuds/actions/runs/11312189955), or built openfreebuds manually in branch `release/v0.15.0`.

**Comment by Fares-Elkady** [comment]
Installed the new release and got the bugreport message like this (or similar):

![openfreebuds_zMFEKw9DUl](https://github.com/user-attachments/assets/3019dbae-df62-44ba-978c-5833ab361f79)
![openfreebuds_Pzr61bFSkG](https://github.com/user-attachments/assets/0975e848-9441-4449-8344-a2588ad37c6d)

Then the app process showed in task manager but the window or taskbar icon wasn't so I made this report:

[OpenFreebuds_report - Copy.log](https://github.com/user-attachments/files/17355365/OpenFreebuds_report.-.Copy.log)

Then deleted the appdata folder and reran it. The app worked like normal but didn't detect the headphones or at least didn't show any signs of it so I made this report: (bluetooth address & username anonymized)

[OpenFreebuds_report2 - Copy.log](https://github.com/user-attachments/files/17355363/OpenFreebuds_report2.-.Copy.log)

Says something about type error trying to iterate an integer in the 6i implementation files. So, perhaps some minor changes in the way data is sent between 5i and 6i happened?

**Comment by melianmiko** [comment]
Fixed, could you please [try again](https://github.com/melianmiko/OpenFreebuds/actions/runs/11314097720)?

**Comment by Fares-Elkady** [comment]
Yep, works perfectly now all functions working. Nice job man 👌

**Comment by melianmiko** [comment]
Wonderful, I'll close this issue after the 0.15.0 release.
